### ISSUE TITLE
Error: contact maintainers [unknown type]: undefined

### ISSUE THREAD

**Issue by 99Kies** [CosmWasm/ts-codegen#156]
this is my contract generate code info:
```
$ cosmwasm-ts-codegen generate \
    --plugin client \
    --schema ./schema \
    --out ./ts \
    --name AMaci
? [bundle] enable bundle? No

Error: contact maintainers [unknown type]: undefined
    at getType (/Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:261:13)
    at getArrayTypeFromItems (/Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:95:24)
    at getArrayTypeFromItems (/Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:91:28)
    at getTypeInfo (/Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:168:18)
    at getPropertyType (/Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:283:18)
    at getPropertySignatureFromProp (/Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:361:5)
    at /Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:386:12
    at Array.map (<anonymous>)
    at getParamsTypeAnnotation (/Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:385:26)
    at createTypedObjectParams (/Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:426:24)
{
  "type": "object",
  "required": [
    "deactivate_message"
  ],
  "properties": {
    "deactivate_message": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Uint256"
        }
      }
    }
  },
  "additionalProperties": false
} deactivate_message
/Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:261
      throw new Error('contact maintainers [unknown type]: ' + type);
            ^

Error: contact maintainers [unknown type]: undefined
    at getType (/Users/feng/.nvm/versions/node/v18.12.1/lib/node_modules/@cosmwasm/ts-codegen/node_modules/wasm-ast-types/main/utils/types.js:261:13)
```

**Comment by 99Kies** [comment]
this is my `deactivate_message` type:

```rust
    UploadDeactivateMessage {
        deactivate_message: Vec<Vec<Uint256>>,
    },
```
